<?php

namespace App\Filament\Resources\WorkReports\Pages;

use App\Filament\Resources\WorkReports\WorkReportResource;
use Filament\Resources\Pages\CreateRecord;

class CreateWorkReport extends CreateRecord
{
    protected static string $resource = WorkReportResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        dd($data);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
